# Site settings
title: XIANG ZHANG
description: XIANG ZHANG'S PERSONAL PAGE
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: XIANG ZHANG
user_description: I'm currently a second year PhD student at department of Geography, McGill Univerisy. 
user_title: PhD student at Mcgill University
email: xiang.zhang7 at mail.mcgill.ca
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum


exclude: ['package.json', 'src' , 'node_modules']
